# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdaad2bb0db4e9bd3d6d574a18a5513817cc51ad815c4e280587d6ea5d34f95797c3225e9ca6c19242f4cd438ab3df70df2e362c35cc95e109762301c5a188ff

test:
  secret_key_base: b12a8d0b29668ffceab0adf53e5d1ed36461eaf33acd819fef32b3aa00c2e80dd57c662f9e302d910cdbdbb0f085d3b7ae1e1bd4660f97e534e4621bdf99e6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
